### PR TITLE
Hover Button Designs Added

### PR DESCRIPTION
**Pull request by curious-vv1**
Closes # 

## ✅ Checks

- [☑️ ] My pull request adheres to the code style of this project
- [ ] If my code requires changes to the documentation I have updated the documentation as required.
- [ ☑️] All the tests have passed

### CODE REVIEW

**Comment by ImBIOS** [comment]
Please provide description and review the PR carefully 😁

**Review by ImBIOS — CHANGES_REQUESTED** [review]
Give a preview in the description so we -as maintainers- know what you build.

**Comment by curious-vv1** [comment]
i have build buttons with different hover animation designs.Its preview as asked:-
send3

**Review by ImBIOS — APPROVED** [review]
LGTM!

**Pull request merged**
